FROM unit9/dind:latest
MAINTAINER Kamil Cholewinski <kamil.cholewinski@unit9.com>

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
            python-flask \
            && \
    rm -rf /var/cache/apt /var/lib/apt/lists

EXPOSE 8600
ADD run /etc/service/inspector/run
ADD main.py /app/main.py
