FROM unit9/nginx:latest

MAINTAINER Artiom Vasiliev <artiom@unit9.com>

RUN apt-get update && \
    apt-get install -y php5 php5-common php5-curl php5-fpm php5-gd \
        php5-mysql php5-xmlrpc php5-xcache php5-memcache && \
    rm -rf /var/cache/apt /var/lib/apt/lists/*

EXPOSE 80

COPY ["php-fpm.run", "/etc/service/php-fpm/run"]
COPY ["vhost.conf", "/etc/nginx/sites-available/default"]
