#
# Nexus data-container for thirdparty repo's.
#
# This docker image uses CentOS 6 as the base OS (CentOS 7's systemd gives problems in a Docker environment atm),
#
FROM    jboss/base

MAINTAINER ddoyle <ddoyle@redhat.com>

# Create a user in our data-volume so we can correctly map access rights.
#RUN useradd -r -m  -s /sbin/nologin -c "JBoss user" -p jboss@01 jboss

# Create the directory for all JBoss product installations.
USER root
RUN mkdir -p /bpms-data && chown -R jboss:jboss /bpms-data
USER jboss

# Data volume for the nexus-repo's
VOLUME ["/bpms-data"]


