FROM appropriate/curl
MAINTAINER svlentink <sander@superbuddy.nl>

#RUN ln -s /bin/sh /bin/bash
RUN apk add --update bash python && rm -rf /var/cache/apk/*

COPY entrypoint.sh /usr/local/bin/entrypoint

ENTRYPOINT ["/usr/local/bin/entrypoint"]
