#
# Node.js w/ Bower & Gulp Dockerfile
#
# https://github.com/dockerfile/nodejs-bower-gulp
#

# Pull base image.
FROM dockerfile/nodejs

RUN echo fs.inotify.max_user_watches=100000 | tee -a /etc/sysctl.conf 
# Install Bower & Gulp
RUN npm install -g bower gulp
ADD run.sh /run.sh
# Define working directory.
WORKDIR /data

# Define default command.
CMD ["/run.sh"]
