FROM golang:1.7-alpine
ARG GOR_VERSION
RUN apk add --no-cache ca-certificates curl
RUN curl -O -L https://github.com/buger/gor/releases/download/v${GOR_VERSION}/gor_v${GOR_VERSION}_x64.tar.gz \
    && tar xzf gor_v${GOR_VERSION}_x64.tar.gz \
    && rm -rf gor_v${GOR_VERSION}_x64.tar.gz
ENTRYPOINT ["./gor"]
