FROM lonelyplanet/scala

MAINTAINER Rob Ulejczyk <rulejczyk@gmail.com>

ENV ASPECTJ_PATH=/root/.aspectj ASPECTJ_VERSION=1.8.9
ENV ASPECTJ_BINARY=$ASPECTJ_PATH/aspectjweaver.jar

RUN mkdir -p $ASPECTJ_PATH && curl -o $ASPECTJ_BINARY http://central.maven.org/maven2/org/aspectj/aspectjweaver/$ASPECTJ_VERSION/aspectjweaver-$ASPECTJ_VERSION.jar
