FROM ubuntu:12.04

LABEL description="Provides the siege load testing tool."

# install siege and cleanup unnecessary files
RUN apt-get update -q && \
  apt-get install siege -q -y && \
  rm -rf /var/lib/apt/lists/*

