# create your custom drupal image here, based of official drupal
#from https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements
FROM drupal:8.2

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/

WORKDIR /var/www/html/themes

USER www-data

RUN git clone --branch 8.x-3.x --single-branch --depth 1 https://git.drupal.org/project/bootstrap.git

USER root

WORKDIR /var/www/html
