FROM alpine:latest

ENV PACKAGES "python py-pip"

RUN apk add --update $PACKAGES
RUN pip install --upgrade pip
RUN pip install awscli \
    && apk --purge -v del py-pip \
    && rm -rf /var/cache/apk/*

RUN mkdir /opt
WORKDIR /opt
