# Version: 1
# Name: zabbix.db
FROM monitoringartist/zabbix-3.0-xxl:latest

MAINTAINER "boyan.au@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

# In case someone loses the Dockerfile
RUN rm -rf /etc/Dockerfile
ADD Dockerfile /etc/Dockerfile

ENV ODBC_CONFIG /config/odbc

RUN mkdir -p "$ODBC_CONFIG" && \ 
        echo " " > "$ODBC_CONFIG"/odbc.ini && \
        ln -sf "$ODBC_CONFIG"/odbc.ini /etc/odbc.ini
        

