FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        openjpeg-tools \
        python-pip \
        python-dev \
        python-gdal \
        ruby \
    && \
    rm -rf /var/lib/apt/lists/*

COPY . /usr/src/

WORKDIR /usr/src/

RUN pip install -r python_requirements.txt
