FROM centos:6.7

# install system dependencies
RUN sed -i -e 's:keepcache=0:keepcache=1:' /etc/yum.conf && \
    yum -y install https://s3.amazonaws.com/exchange-development-yum/exchange-development-repo-1.0.0.noarch.rpm && \
    yum -y update && \
    yum -y install boundless-vendor-libs \
                   bzip2-devel \
                   db4-devel \
                   expat-devel \
                   freetype-devel \
                   gcc \
                   gcc-c++ \
                   gdbm-devel \
                   git \
                   libjpeg-turbo-devel \
                   libtiff-devel \
                   libxml2-devel \
                   libxslt-devel \
                   make \
                   openldap-devel \
                   openssl-devel \
                   python27-devel \
                   python27-virtualenv \
                   readline-devel \
                   sqlite-devel \
                   tk-devel \
                   unzip \
                   wget \
                   zlib-devel \
                   java-1.8.0-openjdk

# download jetty-runner
RUN curl -o /tmp/jetty-runner.jar \
         http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.3.8.v20160314/jetty-runner-9.3.8.v20160314.jar
