FROM uken/precise
MAINTAINER Uken Ops "ops@uken.com"
ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get -y update && apt-get -y install python-dev libpq-dev python-setuptools supervisor git-core python-pip
RUN pip install uwsgi

VOLUME ["/build"]
VOLUME ["/cache"]
