FROM uken/trusty
MAINTAINER Uken Ops "ops@uken.com"
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN curl -sL https://deb.nodesource.com/setup | bash -

RUN apt-get -y update && apt-get -y install nodejs build-essential

RUN mkdir /root/.ssh
RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

WORKDIR /app

