FROM nginx
MAINTAINER Timothy Hnat twhnat@memphis.edu

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key
