FROM avvo/alpine
MAINTAINER Avvo Infrastructure Team <infrastructure@avvo.com>

RUN apk update && \
    apk add ruby ruby-irb ruby-dev ruby-io-console ruby-json ruby-bigdecimal ca-certificates && \
    gem install --no-document bundler -v 1.15.0 && \
    mkdir -p /srv
RUN rm -f /var/cache/apk/*

CMD ["/usr/bin/ruby", "--version"]
