FROM oraclelinux:7-slim
ENV PACKAGE_URL https://repo.mysql.com/yum/mysql-5.6-community/docker/x86_64/mysql-community-server-minimal-5.6.36-2.el7.x86_64.rpm

# Default account to be used if no values set on container start
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD pimpmycloset01
ENV MYSQL_ROOT_PASSWORD pimpmycloset01

# ARG shop_db_name
# ARG shop_db_dump
# ARG operations_db_name
# ARG operations_db_dump
# ARG order_returns_db_name
# ARG order_returns_db_dump

# Install server
RUN rpmkeys --import http://repo.mysql.com/RPM-GPG-KEY-mysql \
  && yum install -y $PACKAGE_URL \
  && yum install -y libpwquality \
  && yum install -y gzip \
  && rm -rf /var/cache/yum/*

RUN mkdir /docker-entrypoint-initdb.d /dump

VOLUME /var/lib/mysql

COPY docker-entrypoint.sh /entrypoint.sh
COPY database-restore.sh /docker-entrypoint-initdb.d/database-restore.sh
ADD dump /dump
# RUN curl -o /dump/$shop_db_name "$shop_db_dump"
# RUN curl -o /dump/$operations_db_name "$operations_db_dump"
# RUN curl -o /dump/$order_returns_db_name "$order_returns_db_dump"
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]
