FROM drupal
# NO FUNCIONA LA CREACION ANIDADA, Y LOS CREA DE PROPIETARIO ROOT
RUN /bin/bash -c 'mkdir -pv ./{modules,profiles,themes,sites};mkdir -pv ./sites/default;mkdir -pv ./sites/default/files;mkdir -pv ./sites/default/files/translations'