FROM ubuntu:xenial

RUN apt-get -qq update

RUN apt-get --no-install-recommends -y install \
    curl \
    vim \
    nodejs \
    npm \
    jq

RUN mkdir -p /couch
WORKDIR /couch
RUN echo "set bell-style none" >> ~/.inputrc
RUN echo 'PS1="$ "' >> ~/.bashrc
