FROM tianon/centos:6.3
MAINTAINER Hiroki Yoshioka <irohiroki@gmail.com>

# sshd
RUN yum -y install openssh-server
RUN echo 'root:password' | chpasswd
# generate keys
RUN /etc/init.d/sshd start

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
