FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq

COPY ./provision/torc_dns_scheduler /torc_dns_scheduler
COPY ./provision/config.yml /config.yml

ENV RUST_BACKTRACE=1

ENTRYPOINT ["/torc_dns_scheduler"]
CMD ["--config=/config.yml", "--master=127.0.0.1"]

