FROM nginx:1.12.1
RUN mkdir /etc/nginx/sites-enabled
RUN mkdir /src
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./config/mime.types /etc/nginx/mime.types
COPY ./config/sites-enabled /etc/nginx/sites-enabled
COPY ./src /src
RUN apt-get update
RUN apt-get install nano
EXPOSE 80 443
CMD ["service", "nginx", "start"]
