
#	
# Date:		2014.02.25
# Pupose:	Build a debian based container 
# Author:	Michael Klöckner
# Version:	0.1
#


# use our base image debian/fresh
FROM debian:experimental

# who we are
MAINTAINER Michael Klöckner <mkl AT im7 DOT de>

#
