#
#		Scala/Java/WebApp
# Date:		2014.02.21
# Pupose:	Build a debian based container whith openjdk7, tomcat7 installed
# Author:	Michael Klöckner
# Version:	0.2
#


# use openjdk7 image ubuntu/openjdk7
FROM ubuntu/openjdk7

# who we are
MAINTAINER Michael Klöckner <mkl AT im7 DOT de>


# insall tomcat
RUN apt-get update
RUN apt-get install -y tomcat7
