# Date:         2014.06.05
# Pupose:       provide basic authentification on docker host with nginx
# Author:       Michael Klöckner
# Source: 	http://rigprog.com/docker-recipes/registry-basic-auth.html
# Version:      0.1
#MKL 2014.06.05 REV_0_7_0

FROM  dockerfile/nginx

# who we are
MAINTAINER Michael Klöckner <mkl AT im7 DOT de>



# copy config and auth file
ADD registry.conf /etc/nginx/sites-enabled/registry.conf
ADD registry.auth /etc/nginx/registry.auth
ADD kdocker-web/ /usr/share/nginx/html/
#RUN service nginx restart

#Cleaning up 
#RUN rm -f /var/lib/apt/lists/archive*

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["/usr/sbin/nginx"]

# Expose ports.
EXPOSE 8001


