FROM choosedigital/oracle-java6:latest

RUN mkdir -p /opt/play && cd /opt/play
RUN wget http://downloads.typesafe.com/play/1.2.6/play-1.2.6.zip
RUN unzip play-1.2.6.zip
RUN mv play-1.2.6 /opt/play
RUN update-alternatives --install /usr/bin/play play /opt/play/play-1.2.6/play 1
RUN echo "PLAY_HOME=/opt/play/play-1.2.6" >> /etc/environment
RUN mkdir -p /app

EXPOSE 9000

CMD ["help"]
ENTRYPOINT ["/opt/play/play-1.2.6/play"]
