FROM debian
RUN apt-get update
RUN apt-get install -y python python-pip
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
VOLUME /code
EXPOSE 5000
WORKDIR /code
CMD ./launch-server.sh

