
FROM sparkchain/ubuntu:16.04 

RUN wget https://github.com/MOACChain/moac-core/releases/download/v1.0.2/nuwa-vnode1.0.2.ubuntu.tar.gz

RUN \  
  mkdir -p /moac/ && \
  tar xvzf nuwa-vnode1.0.2.ubuntu.tar.gz  -C /moac/   && \
  mv /moac/nuwa1.0.2/moac  /moac/moac && \
  rm -f  nuwa-vnode1.0.2.ubuntu.tar.gz  && \
  ls /moac/  && \
  cd  /moac/ && \
  printf '\n# export PATH="/moac/:$PATH"' >> /root/.bashrc

# Define working directory.
 WORKDIR /moac/
 VOLUME [ "/root" ]
 EXPOSE  8545

RUN mkdir -p /usr/local/bin/moac/ 
COPY  ./startup.sh /usr/local/bin/moac/startup.sh
RUN chmod +x /usr/local/bin/moac/startup.sh
RUN sed -i 's/\r$//' /usr/local/bin/moac/startup.sh

ENTRYPOINT ["/usr/local/bin/moac/startup.sh"]


# Define default command.
#CMD ["./moac --testnet --rpc --rpcapi=\"chain3,mc,net,personal,admin,debug,miner,txpool,db\" --rpccorsdomain=\"*\""]

#CMD ["./moac", "--testnet", "--rpc", "--rpcaddr=0.0.0.0", "--rpcapi=chain3,mc,net,personal,admin,debug,miner,txpool,db", "--rpccorsdomain=*"]
