FROM insighttoolkit/itksoftwareguide-src
MAINTAINER Matt McCormick <matt.mccormick@kitware.com>

ENV CCACHE_CPP2=true
ADD dashboard.cmake /itksoftwareguide_dashboard.cmake
ADD cmd.sh /cmd.sh
CMD /cmd.sh
