FROM jupyter/notebook:latest
MAINTAINER ITOH Akihiko
VOLUME /notebooks
WORKDIR /notebooks
EXPOSE 8888
ENV PEM_FILE /key.pem
ENV PASSWORD Dont make this your default
ENV USE_HTTP 1

ADD ./notebook.sh /notebook.sh
RUN apt-get -y update && apt-get -y upgrade && chmod u+x /notebook.sh
