FROM akihikoitoh/ubuntu-dev-base
MAINTAINER ITOH Akihiko

USER dev

RUN sudo apt-get update
RUN sudo apt-get upgrade -y

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN wget --no-check-certificate https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
RUN sudo apt-get -y install elixir

