#                                                                     *** dockerfile for PHP 7.1 *** 2017-06-29
#
#  versione per creazione immagine hlite/raspi:php-fpm-002                      Dockerfile-php-003   2017-11-22
#
#  Dockerfile-base per sviluppi su droplet
#
#    Aggiunta delle estensioni mysql al PHP
#
#    richiamato da docker-compose-008.yml
#
#
#########

FROM php:7.1-fpm
MAINTAINER FP-vmatic  <info@videomatics.com>

# install the PHP extensions
RUN set -ex; \
	\
	apt-get update; \
	apt-get install -y \
		libjpeg-dev \
		libpng12-dev \
	; \
	rm -rf /var/lib/apt/lists/*; \
	\
	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
	docker-php-ext-install gd mysqli opcache

# TODO consider removing the *-dev deps and only keeping the necessary lib* packages

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=2'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
