FROM alpine_base
# FROM centos_base
# FROM centos6_base
# FROM debian_base
# FROM ubuntu_base

LABEL MAINTAINER="WaterBolik@163.com"

VOLUME /usr/src

WORKDIR /usr/src

RUN set -euxo pipefail \
    && apk add --update --no-cache \
        glances \
        htop \
        iotop \
        nmap \
        procps \
        psmisc \
        lshw \
        lsscsi \
        util-linux \
        coreutils \
    && rm -rf /var/cache/apk/*
    # lshw：Hardware Lister
    # util-linux：Random collection of Linux utilities
    # coreutils：The basic file, shell and text manipulation utilities

EXPOSE 61209

# CMD ["/bin/sh"]
