FROM ubuntu:14.04

# Install Nginx.
RUN apt-get update && \
  apt-get install -y nginx && \
  echo "\ndaemon off;" >> /etc/nginx/nginx.conf

# Define mountable directories.
# VOLUME ["/usr/share/nginx/html/dart", "/etc/nginx/sites-enabled", "/var/log/nginx"]
# 
# === HOST ===== 
# mkdir /var/darttar && cd /var/darttar
# wget http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
# unzipp dartsdk-linux-x64-release.zip
# tar zcvf dartsdk-linux-x64-release.tar.gz dart-sdk
# docker build -t test/img .
# docker run -d -p 80:80 -v /var/darttar:/usr/share/nginx/html/dart test/img
# wget http://localhost/dart/dartsdk-linux-x64-release.tar.gz -O /tmp/dartsdk.tgz
VOLUME ["/usr/share/nginx/html/dart"]

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Expose ports.
EXPOSE 80
EXPOSE 443
